### ISSUE TITLE
Skipping some numbers in multiscreen mode

### ISSUE THREAD

**Issue by vdimir** [justbuchanan/i3scripts#11]
I found numbering a little bit strange. I found some information about it in code, but why we need do keep gap in numbering?
As I understand if we remove following lines we got standard behavior, but what problems may occurs with it?
https://github.com/justbuchanan/i3scripts/blob/52a39abd6371f7c9d03c9bbc1a08f33a833cb6a4/autoname_workspaces.py#L117

**Comment by justbuchanan** [comment]
I leave a gap in numbers to help the `new_workspace.py` script work. That script creates a new workspace on the current monitor using the first available number (the number that's skipped) and optionally moves the currently focused window/container to it. See the code here: https://github.com/justbuchanan/i3scripts/blob/52a39abd6371f7c9d03c9bbc1a08f33a833cb6a4/new_workspace.py#L32-L33.

Thinking about this some more, it should be possible to do what I want without skipping the number and I might be able to change it to do so.
