### ISSUE TITLE
i3 autoname workspaces

### ISSUE THREAD

**Issue by SylEleuth** [justbuchanan/i3scripts#19]
There was similar question some time ago but it was never clarified what to do.

```
Traceback (most recent call last):                                                                                                   
  File "./autoname-workspaces.py", line 39, in <module>
    from util import *
ModuleNotFoundError: No module named 'util'
```

I'm new to python and I'm not sure what I have to do. Any help?

**Comment by justbuchanan** [comment]
The util.py file is part of this repo (https://github.com/justbuchanan/i3scripts/blob/master/util.py). You'll need to download it and put it in the same folder as the main autoname_workspaces.py file.

**Comment by SylEleuth** [comment]
Now it works, thank You.
