### ISSUE TITLE
autoname_workspaces name error

### ISSUE THREAD

**Issue by fn-ix** [justbuchanan/i3scripts#27]
Hi!

Now I'm getting another error:

````
$ python .local/share/i3/autoname_workspaces.py 
Traceback (most recent call last):
  File ".local/share/i3/autoname_workspaces.py", line 220, in <module>
    rename_workspaces(i3, icon_list_format=args.icon_list_format)
  File ".local/share/i3/autoname_workspaces.py", line 147, in rename_workspaces
    new_icons = format_icon_list(icon_list, icon_list_format)
NameError: name 'format_icon_list' is not defined
````

**Comment by justbuchanan** [comment]
There were some recent changes to the script that rely on corresponding changes to [util.py](https://github.com/justbuchanan/i3scripts/blob/master/util.py). If you update that file to the same version as autoname_workspaces.py, it should work.

**Comment by fn-ix** [comment]
Yeah that worked! I looked at the last commit date before but didn't think 2 months ago was recent enough. :)
