### ISSUE TITLE
Autorename script keeps renumbering workspaces

### ISSUE THREAD

**Issue by fn-ix** [justbuchanan/i3scripts#40]
Hello!

The `autoname_workspaces.py` script keeps renumbering workspaces even after setting `RENUMBER_WORKSPACES = False`. I tried fiddling with the relevant section in the code too, but was unsuccessful :'(

**Comment by justbuchanan** [comment]
You should just be able to pass `--norenumber_workspaces` when launching the script - let me know if that doesn't work.
