### ISSUE TITLE
Issue with renaming workspaces

### ISSUE THREAD

**Issue by inql** [justbuchanan/i3scripts#6]
Hello, im very impressed about your i3 autoname script, but i've got a problem, while using it with polybar.
I've changed my i3 config file to:
`
bindsym $mod+1 workspace number 1`

And when i create my new workspace, everything works just fine. But when i run any process it shows up as following:

![2018-01-26-182048_421x18_scrot](https://user-images.githubusercontent.com/23345084/35452069-a7d85212-02c5-11e8-8b27-640417ed4dab.png)

It's pretty annoying, because i have to remember number of the workspace to navigate them efficiently.

My polybar i3 module is set to show '%name' of the workspace.
Any ideas? I can send more information if needed. I really would like to deal with it on my own, but my knowledge about python is pretty basic :)

Have a nice day!

**Comment by justbuchanan** [comment]
@inql I see you closed this - were you able to figure it out? I'm curious to know what fixed it :)

**Comment by inql** [comment]
just set in my polybar to show `%index% : %name%`
it shows workspaces as `workspace num : workspace num ` - like `1 : 1` when theres no processes there, but when i run something it works pretty cool. Maybe i will be able to fix that in future, but im new to i3wm and generally linux (it's like 6 month since i start using linux and im using i3wm for a month) :)

**Comment by justbuchanan** [comment]
Sounds great! Glad it's working for you.
