### ISSUE TITLE
Working with another WM's and another fonts

### ISSUE THREAD

**Issue by edn9** [justbuchanan/i3scripts#9]
Hello Dev! First of all thank you for the script, its so good to see my WM bar working just like a regular DE bar.

I want to know if its possible to this script work with another WM's, like 2bwm n stuff.
Also I have Icomoon, and I find a way to make it work properly, not with everything but at last its working. Did I miss something? How do I make to use every icon?

Thanks for the work!
https://icomoon.io/

MPV with Icomoon font: http://i.imgur.com/NAx9bKs.png
http://i.imgur.com/RnR6kGz.png

**Comment by edn9** [comment]
Ps: I want to make new fonts for programs like gimp, krita, qutebrowser, etc, can my draws work as a icon too?

**Comment by justbuchanan** [comment]
Hi @necronoise, glad you've found this useful!

It should be possible to make this script work with other WM's like 2bwm, but it will take some work to adapt it. This script uses `i3ipc` as a mechanism for talking to i3. It's used to listen for window events and to set the titles/icons in the status bar. If you want to adapt this script to a different WM, you'll likely need an equivalent of `i3ipc` that's specific to that WM.

Cool to see that you got icomoon working! Can you clarify what issues you're having when trying to add icons for gimp, krita, etc? It should work fine as long as you get the window names for those programs (see the comment about WM_CLASS in autoname_workspaces.py).

**Comment by edn9** [comment]
The 2bwm use xtitle, do I need to know advanced python programming skills to make it work? I'm really low level at it.

About the Icons I want to use and make new icons too, but looks like only "<private use>" work, hmm. http://i.imgur.com/jL0LXPy.png

**Comment by edn9** [comment]
Just a lil update, I'm finally found how to make [fonts](https://github.com/necronoise/necrofont) and everything its working 100% with your script! Thanks again. :)



Now I just need to have a time to make it work with anothers WM.

**Comment by justbuchanan** [comment]
Great, glad to hear you got the fonts working!

I haven't used 2bwm before, so I'm afraid I'm not much help there :/. From a quick look at the github repo, I don't think 2bwm provides any sort of ipc interface (although I could be wrong). The ipc interface that i3 provides makes it easy for my python script to ask i3 things like "which window is currently focused?", "list all windows on all workspaces", and "let me know when window is created or deleted". Without 2bwm providing a similar interface, it would be very difficult to get something like this python script to work.

**Comment by edn9** [comment]
Thank you! And damn, well, I gotta check it with careful, I'm luck to have a lot of friends who use other WM's so I will try to get some help too.

**Comment by justbuchanan** [comment]
No problem, and best of luck!
